apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: node-deployment
  labels:
    app: node
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: node    
  # pod template
  template:
    metadata:
      labels:
        app: node
    spec:
      # pod contains 1 container
      containers:
      - name: node
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        # container opens port 22137
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP